version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: file-search-postgres-test
    environment:
      POSTGRES_DB: file_search_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d file_search_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
