services:
  database:
    image: postgres:16-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=myuserpassword
      - POSTGRES_DB=file-search
    container_name: 'postgres-for-testing'
    ports:
      - '54320:5432'
    tmpfs: /var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d file-search']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
